# Generated by Django 5.0.7 on 2024-09-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='project_id',
            new_name='project',
        ),
    ]
